pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'todo-api'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build -t todo-api .'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    echo 'No automated tests yet'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -d -p 9000:9000 todo-api'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'docker system prune -f'
        }
    }
}
